package com.enterprise.banking.ai.execution;

import com.enterprise.banking.ai.exception.AiExtensionException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testng.TestListenerAdapter;
import org.testng.TestNG;

import javax.tools.JavaCompiler;
import javax.tools.ToolProvider;
import java.io.File;
import java.net.URL;
import java.net.URLClassLoader;

/**
 * Orchestrates the dynamic compilation and execution of AI-generated TestNG test classes.
 * Leverages the Java Compiler API and TestNG programmatic execution to run synthesized 
 * test suites seamlessly, generating consolidated Execution Reports for the orchestrator.
 */
public class ExecutionCoordinator {

    private static final Logger LOGGER = LoggerFactory.getLogger(ExecutionCoordinator.class);

    /**
     * Default constructor for framework instantiation.
     */
    public ExecutionCoordinator() {
        // Intentionally left empty for framework initialization
    }

    /**
     * Legacy execution pipeline alias required by existing end-to-end framework tests.
     * Routes the string-based path parameters to the core File-based compilation logic.
     *
     * @param sourcePath       The physical directory or file path of the generated source.
     * @param executionContext The operational context or environment parameter (e.g., "QA", "UAT").
     * @return ExecutionReport containing the summarized metrics.
     * @throws IllegalArgumentException if the provided source path is invalid.
     */
    public ExecutionReport runExecutionPipeline(String sourcePath, String executionContext) {
        LOGGER.info("Routing legacy execution pipeline request for context: {}", executionContext);
        if (sourcePath == null || sourcePath.trim().isEmpty()) {
            LOGGER.error("Execution pipeline invoked with null or empty source path.");
            throw new IllegalArgumentException("Source path cannot be null or empty for execution pipeline.");
        }
        
        File generatedSourceFile = new File(sourcePath);
        return compileAndExecute(generatedSourceFile);
    }

    /**
     * Compiles the dynamically generated Selenium source code, loads it into the JVM, 
     * executes it using TestNG, and extracts the test metrics.
     *
     * @param generatedSourceFile The physical Java source file generated by the AI engine.
     * @return ExecutionReport containing the execution metrics and simulated report paths.
     * @throws AiExtensionException if compilation, class loading, or execution fails.
     */
    public ExecutionReport compileAndExecute(File generatedSourceFile) {
        if (generatedSourceFile == null || !generatedSourceFile.exists()) {
            LOGGER.error("Generated source file is null or does not exist on the file system.");
            throw new IllegalArgumentException("Valid generated source file is required for execution.");
        }

        LOGGER.info("Initiating dynamic compilation for source file: {}", generatedSourceFile.getAbsolutePath());

        try {
            // Stage 1: Dynamic Java Compilation
            compileSourceFile(generatedSourceFile);

            // Stage 2: Dynamic Class Loading
            Class<?> testClass = loadCompiledClass(generatedSourceFile);

            // Stage 3: Programmatic TestNG Execution
            return executeTestNgSuite(testClass);

        } catch (Exception exception) {
            LOGGER.error("Critical failure encountered during the dynamic execution pipeline.", exception);
            throw new AiExtensionException("Failed to compile and execute the generated test suite.", exception);
        }
    }

    /**
     * Invokes the system Java Compiler to transform the .java file into a .class file.
     *
     * @param sourceFile The target Java file.
     * @throws AiExtensionException if the compilation fails or the compiler is unavailable.
     */
    private void compileSourceFile(File sourceFile) {
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        if (compiler == null) {
            throw new AiExtensionException("System Java Compiler is unavailable. Ensure the framework is running on a JDK, not a JRE.");
        }

        // IMPORTANT: without an explicit "-d" destination, javac writes the compiled .class
        // file flat, in the SAME directory as the .java source - it ignores the package
        // declaration entirely and does NOT create a matching com/enterprise/.../ directory
        // tree. But loadCompiledClass() below builds a URLClassLoader rooted at that same flat
        // directory and asks for the fully-qualified class name (with the "generated" package),
        // which a URLClassLoader can only resolve if the .class file lives in a matching nested
        // package directory under the classloader's root. Passing "-d" here makes javac create
        // that expected package-directory structure so the two agree on where the class lives.
        //
        // Also use getAbsoluteFile().getParentFile() rather than getParentFile() directly:
        // for a relative, single-segment path (e.g. new File("generated-code"), with no
        // directory separator), getParentFile() returns null, which previously NPE'd here.
        // The absolute form always has a parent (the current working directory) unless the
        // path resolves to the filesystem root.
        String destinationDir = sourceFile.getAbsoluteFile().getParentFile().getAbsolutePath();
        int compilationResult = compiler.run(null, null, null, "-d", destinationDir, sourceFile.getAbsolutePath());
        if (compilationResult != 0) {
            throw new AiExtensionException("Dynamic compilation failed for file: " + sourceFile.getName());
        }
        
        LOGGER.debug("Dynamic compilation successful for: {}", sourceFile.getName());
    }

    /**
     * Loads the compiled .class file into the JVM using a URLClassLoader.
     *
     * @param sourceFile The original source file used to derive the class name and location.
     * @return The loaded Class representation.
     * @throws Exception if URL conversion or class finding fails.
     */
    private Class<?> loadCompiledClass(File sourceFile) throws Exception {
        File parentDirectory = sourceFile.getAbsoluteFile().getParentFile();
        URL[] urls = new URL[]{parentDirectory.toURI().toURL()};
        
        // Extract the raw class name without the .java extension
        String className = sourceFile.getName().replace(".java", "");
        
        // The generator defines the package as com.enterprise.banking.tests.generated
        String fullyQualifiedClassName = "com.enterprise.banking.tests.generated." + className;
        
        try (URLClassLoader classLoader = URLClassLoader.newInstance(urls, this.getClass().getClassLoader())) {
            Class<?> loadedClass = Class.forName(fullyQualifiedClassName, true, classLoader);
            LOGGER.debug("Class successfully loaded into JVM: {}", fullyQualifiedClassName);
            return loadedClass;
        } catch (ClassNotFoundException exception) {
            LOGGER.error("Failed to locate compiled class in the classloader: {}", fullyQualifiedClassName);
            throw new AiExtensionException("Classloader resolution failed.", exception);
        }
    }

    /**
     * Executes the loaded TestNG class programmatically and extracts execution metrics.
     *
     * @param testClass The dynamically loaded test suite class.
     * @return The populated ExecutionReport.
     */
    private ExecutionReport executeTestNgSuite(Class<?> testClass) {
        LOGGER.info("Executing dynamically loaded TestNG suite: {}", testClass.getSimpleName());

        TestNG testngEngine = new TestNG();
        testngEngine.setTestClasses(new Class[]{testClass});
        
        TestListenerAdapter metricsListener = new TestListenerAdapter();
        testngEngine.addListener(metricsListener);
        
        // Run the suite programmatically
        testngEngine.run();

        int passed = metricsListener.getPassedTests().size();
        int failed = metricsListener.getFailedTests().size();
        int skipped = metricsListener.getSkippedTests().size();
        int total = passed + failed + skipped;

        ExecutionReport report = new ExecutionReport(total, passed, failed, skipped);
        report.setExtentReportPath(System.getProperty("user.dir") + "/target/reports/ExtentReport.html");
        report.setAllureReportPath(System.getProperty("user.dir") + "/target/allure-results");

        LOGGER.info("TestNG Execution Completed. Total: {}, Passed: {}, Failed: {}, Skipped: {}", 
                total, passed, failed, skipped);
        
        return report;
    }
}