package com.enterprise.banking.pages;

import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class AccountOverviewPage {

    private WebDriverWait wait;

    // --- Locators ---
    @FindBy(xpath = "//h1[contains(text(),'Accounts Overview')]")
    private WebElement pageHeader;

    @FindBy(xpath = "//*[@id='accountTable']//tbody/tr[1]/td[2]")
    private WebElement textAccountBalance;

    @FindBy(linkText = "Log Out")
    private WebElement btnLogout;

    @FindBy(linkText = "Accounts Overview")
    private WebElement linkAccountsOverview;

    // --- Constructor ---
    public AccountOverviewPage(WebDriver driver) {
        PageFactory.initElements(driver, this);
        wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    }

    // --- Standard Methods ---
    public boolean isHeaderDisplayed() {
        wait.until(ExpectedConditions.visibilityOf(pageHeader));
        return pageHeader.isDisplayed();
    }

    public String getAccountBalance() {
        wait.until(ExpectedConditions.visibilityOf(textAccountBalance));
        return textAccountBalance.getText();
    }

    public void clickLogout() {
        wait.until(ExpectedConditions.elementToBeClickable(btnLogout)).click();
    }

    // --- Added for Hybrid E2E Test ---

    public void navigateToOverview() {
        wait.until(ExpectedConditions.elementToBeClickable(linkAccountsOverview)).click();
    }

    public boolean isAccountPresent(String targetAccountId) {
        try {
            // Dynamic locator to find the specific account row generated by the API
            WebElement accountLink = wait.until(ExpectedConditions.visibilityOfElementLocated(
                    By.xpath("//a[text()='" + targetAccountId + "']")));
            return accountLink.isDisplayed();
        } catch (Exception e) {
            return false;
        }
    }

    public String getAccountBalance(String targetAccountId) {
        // Dynamic locator to fetch balance matching the API generated account
        WebElement balanceData = wait.until(ExpectedConditions.visibilityOfElementLocated(
                By.xpath("//a[text()='" + targetAccountId + "']/../following-sibling::td[1]")));
        return balanceData.getText();
    }
}