package com.enterprise.banking.pages;

import java.time.Duration;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.enterprise.banking.config.SiteProfileLoader;
import com.enterprise.banking.utils.LocatorParser;

public class AccountOverviewPage {

    private WebDriverWait wait;
    private SiteProfileLoader profileLoader;

    // --- Constructor ---
    public AccountOverviewPage(WebDriver driver, SiteProfileLoader profileLoader) {
        this.wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        this.profileLoader = profileLoader;
    }

    // --- Standard Methods ---
    public boolean isHeaderDisplayed() {
        WebElement pageHeader = wait.until(ExpectedConditions.visibilityOfElementLocated(LocatorParser.parseLocator(profileLoader.getLocator("accountOverview", "pageHeader"))));
        return pageHeader.isDisplayed();
    }

    public String getAccountBalance() {
        return wait.until(ExpectedConditions.visibilityOfElementLocated(LocatorParser.parseLocator(profileLoader.getLocator("accountOverview", "textAccountBalance")))).getText();
    }

    public void clickLogout() {
        wait.until(ExpectedConditions.elementToBeClickable(LocatorParser.parseLocator(profileLoader.getLocator("accountOverview", "btnLogout")))).click();
    }

    // --- Added for Hybrid E2E Test ---

    public void navigateToOverview() {
        wait.until(ExpectedConditions.elementToBeClickable(LocatorParser.parseLocator(profileLoader.getLocator("accountOverview", "linkAccountsOverview")))).click();
    }

    public boolean isAccountPresent(String targetAccountId) {
        try {
            // Dynamic locator to find the specific account row generated by the API
            String locatorString = String.format(profileLoader.getLocator("accountOverview", "accountLink"), targetAccountId);
            WebElement accountLink = wait.until(ExpectedConditions.visibilityOfElementLocated(LocatorParser.parseLocator(locatorString)));
            return accountLink.isDisplayed();
        } catch (Exception e) {
            return false;
        }
    }

    public String getAccountBalance(String targetAccountId) {
        // Dynamic locator to fetch balance matching the API generated account
        String locatorString = String.format(profileLoader.getLocator("accountOverview", "balanceData"), targetAccountId);
        WebElement balanceData = wait.until(ExpectedConditions.visibilityOfElementLocated(LocatorParser.parseLocator(locatorString)));
        return balanceData.getText();
    }
}