package com.enterprise.banking.ai.execution.orchestrator;

import com.enterprise.banking.ai.execution.model.ExecutionHistory;
import com.enterprise.banking.ai.execution.model.ExecutionMetrics;
import com.enterprise.banking.ai.execution.model.ExecutionPlan;
import com.enterprise.banking.ai.execution.model.ExecutionSummary;
import com.enterprise.banking.ai.execution.runtime.RuntimeStatistics;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.LongSummaryStatistics;

/**
 * Aggregates runtime statistics generated by workers into normalized, enterprise-grade summaries.
 */
public class ExecutionResultCollector {

    private final List<ExecutionHistory> historicalRecords;
    private int totalPassed = 0;
    private int totalFailed = 0;
    private int totalSkipped = 0;
    private long totalDuration = 0;
    private final List<Long> allTimings;
    private LocalDateTime globalStartTime;

    /**
     * Initializes the collector and underlying structures.
     */
    public ExecutionResultCollector() {
        this.historicalRecords = new ArrayList<>();
        this.allTimings = new ArrayList<>();
        this.globalStartTime = LocalDateTime.now();
    }

    /**
     * Collects statistics from a single executed plan.
     *
     * @param plan       The executed plan
     * @param statistics Raw statistics returned from the runtime engine
     */
    public synchronized void collect(ExecutionPlan plan, RuntimeStatistics statistics) {
        if (plan != null && statistics != null) {
            totalPassed += statistics.getPassedCount();
            totalFailed += statistics.getFailedCount();
            totalSkipped += statistics.getSkippedCount();
            totalDuration += statistics.getTotalDurationMillis();
            allTimings.addAll(statistics.getExecutionTimings());

            ExecutionHistory history = new ExecutionHistory();
            history.setExecutionId(plan.getPlanId());
            history.setScenarioId(plan.getMappedScenario() != null ? plan.getMappedScenario().getScenario().getScenarioId() : "UNKNOWN");
            history.setExecutionStatus(plan.getStatus().name());
            history.setMappedTest(plan.getMappedTestClass());
            historicalRecords.add(history);
        }
    }

    /**
     * Generates a finalized summary from all collected data.
     *
     * @return ExecutionSummary object
     */
    public ExecutionSummary buildSummary() {
        ExecutionSummary summary = new ExecutionSummary();
        summary.setStartTime(globalStartTime);
        summary.setEndTime(LocalDateTime.now());
        summary.setDurationMillis(totalDuration);
        
        int totalTests = totalPassed + totalFailed + totalSkipped;
        summary.setTotalTests(totalTests);
        summary.setPassed(totalPassed);
        summary.setFailed(totalFailed);
        summary.setSkipped(totalSkipped);
        
        double successRate = totalTests == 0 ? 0.0 : (double) totalPassed / totalTests * 100.0;
        summary.setSuccessRate(Math.round(successRate * 100.0) / 100.0);

        return summary;
    }

    /**
     * Generates analytical metrics from collected data.
     *
     * @return ExecutionMetrics object
     */
    public ExecutionMetrics buildMetrics() {
        ExecutionMetrics metrics = new ExecutionMetrics();
        int totalTests = totalPassed + totalFailed + totalSkipped;

        if (totalTests > 0) {
            metrics.setPassRate((double) totalPassed / totalTests * 100.0);
            metrics.setFailureRate((double) totalFailed / totalTests * 100.0);
        }

        if (!allTimings.isEmpty()) {
            LongSummaryStatistics stats = allTimings.stream()
                    .mapToLong(l -> l == null ? 0L : l)
                    .summaryStatistics();
            
            metrics.setSlowestTestMillis(stats.getMax());
            metrics.setFastestTestMillis(stats.getMin());
            metrics.setAverageExecutionTimeMillis(stats.getAverage());
        }

        return metrics;
    }

    public List<ExecutionHistory> getHistoricalRecords() {
        return new ArrayList<>(historicalRecords);
    }
}