package com.enterprise.banking.tests;

import org.testng.Assert;
import org.testng.annotations.Test;

import com.enterprise.banking.pages.FindTransactionsPage;
import com.enterprise.banking.pages.LoginPage;

public class FindTransactionsTest extends BaseTest {

    // CRITICAL PHASE 3 CUTOVER: Pointing specifically to the new H2DataProvider
    @Test(dataProvider = "h2-login-data", dataProviderClass = com.enterprise.banking.utils.H2DataProvider.class)
    public void verifyFindTransactionsWorkflow(String username, String password, String transferAmount, 
                                               String searchAmount, String searchDate, String searchTransId) {
        
        System.out.println(">>> Executing Find Transactions Test for user: " + username);

        // Step 1: Login
        // FIX: Replaced 'driver' with 'getDriver()' for Thread-Safety
        LoginPage loginPage = new LoginPage(getDriver());
        loginPage.enterUsername(username);
        loginPage.enterPassword(password);
        loginPage.clickLogin();

        // Step 2: Initialize Page Object
        // FIX: Replaced 'driver' with 'getDriver()'
        FindTransactionsPage findTransPage = new FindTransactionsPage(getDriver());

        // Step 3: Validate Search by Amount
        if (searchAmount != null && !searchAmount.isEmpty()) {
            findTransPage.navigateToFindTransactions();
            findTransPage.searchByAmount(searchAmount);
            
            Assert.assertTrue(findTransPage.areTransactionsFound(), 
                    "Assertion Failed: No transactions found for Amount: $" + searchAmount);
            System.out.println(">>> SUCCESS! Found " + findTransPage.getTransactionCount() + " transaction(s) matching Amount: $" + searchAmount);
        }

        // Step 4: Validate Search by Date
        // We click the left menu link again to reload the DOM and reset the AJAX containers
        if (searchDate != null && !searchDate.isEmpty()) {
            findTransPage.navigateToFindTransactions();
            findTransPage.searchByDate(searchDate);
            
            Assert.assertTrue(findTransPage.areTransactionsFound(), 
                    "Assertion Failed: No transactions found for Date: " + searchDate);
            System.out.println(">>> SUCCESS! Found " + findTransPage.getTransactionCount() + " transaction(s) matching Date: " + searchDate);
        }

        /* * Note: Transaction IDs are dynamically generated by the backend. 
         * Unless you dynamically write the ID to the Excel sheet during the Transfer test, 
         * static IDs in the sheet will fail. We skip execution if the Excel cell is empty.
         */
        if (searchTransId != null && !searchTransId.isEmpty()) {
            findTransPage.navigateToFindTransactions();
            findTransPage.searchByTransactionId(searchTransId);
            
            Assert.assertTrue(findTransPage.areTransactionsFound(), 
                    "Assertion Failed: No transactions found for ID: " + searchTransId);
            System.out.println(">>> SUCCESS! Found transaction matching ID: " + searchTransId);
        }

        // Step 5: Clean Logout
        findTransPage.clickLogout();
    }
}