package com.enterprise.banking.ai.data.model;

/**
 * Represents a single distinct data field dynamically generated by the AI data synthesizer.
 * Supports generic object holding to accommodate strings, numbers, and boundary types.
 */
public class GeneratedField {

    private String fieldName;
    private Object fieldValue;
    private String dataType;
    private boolean isNegativePath;

    /**
     * Default constructor for serialization support.
     */
    public GeneratedField() {
    }

    /**
     * Parameterized constructor to explicitly define a generated data point.
     *
     * @param fieldName      The logical name of the field (e.g., "accountNumber")
     * @param fieldValue     The actual synthesized value
     * @param dataType       The expected data type as a string
     * @param isNegativePath Flag indicating if this data is designed to fail validation
     */
    public GeneratedField(String fieldName, Object fieldValue, String dataType, boolean isNegativePath) {
        if (fieldName == null || fieldName.trim().isEmpty()) {
            throw new IllegalArgumentException("Field name cannot be null or empty.");
        }
        this.fieldName = fieldName;
        this.fieldValue = fieldValue;
        this.dataType = dataType;
        this.isNegativePath = isNegativePath;
    }

    public String getFieldName() {
        return fieldName;
    }

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    public Object getFieldValue() {
        return fieldValue;
    }

    public void setFieldValue(Object fieldValue) {
        this.fieldValue = fieldValue;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public boolean isNegativePath() {
        return isNegativePath;
    }

    public void setNegativePath(boolean negativePath) {
        this.isNegativePath = negativePath;
    }

    /**
     * Safely retrieves the field value as a string for web injection.
     * @return String representation of the value, or empty string if null
     */
    public String getValueAsString() {
        return fieldValue != null ? fieldValue.toString() : "";
    }
}