package com.enterprise.banking.ai.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Domain model representing a conceptual Test Scenario.
 * Designed as a hybrid POJO to support both standard JavaBean conventions for the 
 * internal database persister and record-style accessors for legacy framework compatibility.
 */
public class TestScenario {

    // Standard POJO Fields mapped for database persistence
    private String scenarioId;
    private String planId;
    private String scenarioDescription;
    private List<TestCase> testCases;

    // Extended framework fields required by classification and export engines
    private String id;
    private String featureName;
    private String scenarioTitle;
    private String category;
    private String priority;

    /**
     * Default constructor required for framework instantiation and serialization.
     * Safely initializes collections to prevent NullPointerExceptions.
     */
    public TestScenario() {
        this.testCases = new ArrayList<>();
    }

    /**
     * Parameterized constructor required by AiScenarioGeneratorService and ScenarioClassifier.
     * Maps the core attributes generated by the AI model.
     *
     * @param id                  The unique identifier for the scenario.
     * @param featureName         The parent feature or requirement name.
     * @param scenarioTitle       The precise title of the scenario.
     * @param scenarioDescription The descriptive text defining the test boundary.
     * @param category            The classification category (e.g., POSITIVE, NEGATIVE, EDGE_CASE).
     * @param priority            The execution priority (e.g., HIGH, MEDIUM, LOW).
     */
    public TestScenario(String id, String featureName, String scenarioTitle, 
                        String scenarioDescription, String category, String priority) {
        this.id = id;
        this.scenarioId = id; // Maintain synchronization between legacy and modern ID fields
        this.featureName = featureName;
        this.scenarioTitle = scenarioTitle;
        this.scenarioDescription = scenarioDescription;
        this.category = category;
        this.priority = priority;
        this.testCases = new ArrayList<>();
    }

    // ========================================================================
    // Record-style accessors to maintain backward compatibility with 
    // DatabaseToExcelExporter, CoverageAnalyzer, and generator services.
    // ========================================================================

    /**
     * Retrieves the scenario ID using record-style accessor.
     * @return The scenario identifier.
     */
    public String id() {
        return this.id != null ? this.id : this.scenarioId;
    }

    /**
     * Retrieves the associated feature name.
     * @return The feature name.
     */
    public String featureName() {
        return this.featureName;
    }

    /**
     * Retrieves the precise scenario title.
     * @return The scenario title.
     */
    public String scenarioTitle() {
        return this.scenarioTitle;
    }

    /**
     * Retrieves the classification category.
     * @return The scenario category.
     */
    public String category() {
        return this.category;
    }

    /**
     * Retrieves the execution priority.
     * @return The execution priority.
     */
    public String priority() {
        return this.priority;
    }

    // ========================================================================
    // Standard Getters and Setters for modern framework usage and DB persistence
    // ========================================================================

    public String getScenarioId() {
        return scenarioId;
    }

    public void setScenarioId(String scenarioId) {
        this.scenarioId = scenarioId;
        this.id = scenarioId; // Keep synchronized
    }

    public String getPlanId() {
        return planId;
    }

    public void setPlanId(String planId) {
        this.planId = planId;
    }

    public String getScenarioDescription() {
        return scenarioDescription;
    }

    public void setScenarioDescription(String scenarioDescription) {
        this.scenarioDescription = scenarioDescription;
    }

    public List<TestCase> getTestCases() {
        return testCases;
    }

    public void setTestCases(List<TestCase> testCases) {
        this.testCases = testCases != null ? testCases : new ArrayList<>();
    }

    public String getFeatureName() {
        return featureName;
    }

    public void setFeatureName(String featureName) {
        this.featureName = featureName;
    }

    public String getScenarioTitle() {
        return scenarioTitle;
    }

    public void setScenarioTitle(String scenarioTitle) {
        this.scenarioTitle = scenarioTitle;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }
}