package com.enterprise.banking.ai.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Domain model representing a concrete, executable Test Case.
 * Designed as a hybrid POJO to support standard JavaBean conventions for database 
 * persistence and record-style accessors for legacy framework compatibility.
 */
public class TestCase {

    // Standard POJO Fields mapped for database persistence
    private String testCaseId;
    private String scenarioId;
    private String testCaseTitle;
    private String testSteps; // String representation for H2 Database
    private String expectedResult;
    private String status;

    // Extended framework fields required by classification and export engines
    private String objective;
    private String precondition;
    private String priority;
    private String severity;
    private List<TestStep> stepsList;

    /**
     * Default constructor required for framework instantiation, serialization, 
     * and ORM mapping. Safely initializes the list to prevent NullPointerExceptions.
     */
    public TestCase() {
        this.stepsList = new ArrayList<>();
    }

    /**
     * Parameterized constructor for rapid instantiation by AI generator services.
     * Maps the core attributes generated by the AI model.
     *
     * @param testCaseId    The unique identifier for the test case.
     * @param scenarioId    The parent scenario identifier.
     * @param testCaseTitle The descriptive title of the test case.
     * @param objective     The primary objective or goal of the test case.
     * @param precondition  The required state before executing the test.
     * @param priority      The execution priority (e.g., HIGH, MEDIUM, LOW).
     * @param severity      The business impact severity of the test case.
     * @param stepsList     The structured list of executable test steps.
     */
    public TestCase(String testCaseId, String scenarioId, String testCaseTitle, 
                    String objective, String precondition, String priority, 
                    String severity, List<TestStep> stepsList) {
        this.testCaseId = testCaseId;
        this.scenarioId = scenarioId;
        this.testCaseTitle = testCaseTitle;
        this.objective = objective;
        this.precondition = precondition;
        this.priority = priority;
        this.severity = severity;
        this.stepsList = stepsList != null ? stepsList : new ArrayList<>();
        
        // Auto-serialize the list for legacy database string persistence
        this.testSteps = this.stepsList.toString();
    }

    // ========================================================================
    // Record-style accessors to maintain backward compatibility with 
    // DatabaseToExcelExporter, StatisticsGenerator, and TraceabilityGenerator.
    // ========================================================================

    public String testCaseId() {
        return this.testCaseId;
    }

    public String testCaseTitle() {
        return this.testCaseTitle;
    }

    public String objective() {
        return this.objective;
    }

    public String precondition() {
        return this.precondition;
    }

    public String priority() {
        return this.priority;
    }

    public String severity() {
        return this.severity;
    }

    public List<TestStep> steps() {
        return this.stepsList;
    }

    // ========================================================================
    // Standard Getters and Setters for modern framework usage and DB persistence
    // ========================================================================

    public String getTestCaseId() {
        return testCaseId;
    }

    public void setTestCaseId(String testCaseId) {
        this.testCaseId = testCaseId;
    }

    public String getScenarioId() {
        return scenarioId;
    }

    public void setScenarioId(String scenarioId) {
        this.scenarioId = scenarioId;
    }

    public String getTestCaseTitle() {
        return testCaseTitle;
    }

    public void setTestCaseTitle(String testCaseTitle) {
        this.testCaseTitle = testCaseTitle;
    }

    public String getTestSteps() {
        // Fallback synchronization if the string is empty but the list is populated
        if ((this.testSteps == null || this.testSteps.isEmpty()) && this.stepsList != null) {
            return this.stepsList.toString();
        }
        return testSteps;
    }

    public void setTestSteps(String testSteps) {
        this.testSteps = testSteps;
    }

    public String getExpectedResult() {
        return expectedResult;
    }

    public void setExpectedResult(String expectedResult) {
        this.expectedResult = expectedResult;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getObjective() {
        return objective;
    }

    public void setObjective(String objective) {
        this.objective = objective;
    }

    public String getPrecondition() {
        return precondition;
    }

    public void setPrecondition(String precondition) {
        this.precondition = precondition;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public List<TestStep> getStepsList() {
        return stepsList;
    }

    public void setStepsList(List<TestStep> stepsList) {
        this.stepsList = stepsList != null ? stepsList : new ArrayList<>();
        this.testSteps = this.stepsList.toString();
    }
}